FROM squidfunk/mkdocs-material:latest AS BUILD
ARG PLANTUML_VERSION=1.2020.15
ARG JDK_URL=https://cdn.azul.com/zulu/bin/zulu14.29.23-ca-jdk14.0.2-linux_musl_x64.tar.gz
ENV PLANTUML_URL="https://repo1.maven.org/maven2/net/sourceforge/plantuml/plantuml/${PLANTUML_VERSION}/plantuml-${PLANTUML_VERSION}.jar"
RUN apk add --no-cache wget \
    && mkdir -p /opt/jdk \
    && wget -qO- "${JDK_URL}" | tar -xz -f- --strip-components=1 -C /opt/jdk \
    && wget -q -O /usr/local/lib/plantuml.jar "${PLANTUML_URL}" \
    && /opt/jdk/bin/jlink --no-header-files --no-man-pages --compress=2 --strip-debug \
         --add-modules $(/opt/jdk/bin/jdeps --print-module-deps /usr/local/lib/plantuml.jar) \
         --output /opt/customjre

FROM squidfunk/mkdocs-material:latest
ADD plantuml /usr/local/bin/plantuml
RUN pip install --no-cache-dir plantuml-markdown
COPY --from=BUILD /opt/customjre /opt/jre
COPY --from=BUILD /usr/local/lib/plantuml.jar /usr/local/lib/plantuml.jar
ENV PATH=/opt/customjre/bin

# https://github.com/AdoptOpenJDK/openjdk-docker/issues/75
RUN apk add --no-cache fontconfig ttf-dejavu
RUN ln -s /usr/lib/libfontconfig.so.1 /usr/lib/libfontconfig.so && \
    ln -s /lib/libuuid.so.1 /usr/lib/libuuid.so.1 && \
    ln -s /lib/libc.musl-x86_64.so.1 /usr/lib/libc.musl-x86_64.so.1
ENV LD_LIBRARY_PATH /usr/lib

CMD [ "build" ]
